### ISSUE TITLE
Bundlephobia error

### ISSUE THREAD

**Issue by dy** [defijs/defi#6]
https://bundlephobia.com/result?p=defi

Some deps are missing.
Would be nice to get rid of babel runtime too?

**Comment by finom** [comment]
@dy weird, these files are there, I've double checked (I even made some dummy releases). It looks like a bug at bundlephobia or something else I don't understand. Do you have any ideas?

> Would be nice to get rid of babel runtime too?

Defi.js is uses features provided by Babel and they require the runtime as a JS library which needs to be included for any CJS environment.

**Comment by finom** [comment]
@dy OK, I see the issue, fixing.

**Comment by finom** [comment]
Fixed, my bad.

**Comment by dy** [comment]
Thanks @finom!
